"""made changes mysql2

Revision ID: 0a09e14c4bcd
Revises: 
Create Date: 2018-11-05 17:51:45.387556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a09e14c4bcd'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emitent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emitentname', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emitent')
    # ### end Alembic commands ###
