"""add_suser_label

Revision ID: bdbc2a9722c6
Revises: 9a9a88e0e357
Create Date: 2018-12-25 20:49:46.947962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbc2a9722c6'
down_revision = '9a9a88e0e357'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morningdesk', sa.Column('suser_label', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('morningdesk', 'suser_label')
    # ### end Alembic commands ###
